[package]
name = "ProjectG03Alpha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = {path = "lib"}
control = {path = "lib/control"}
winit = "0.28"